Add support heroku & other that using process.env.PORT
metarhia/impress pull request #1467
Opened 2021-02-10 22:29 UTC by imnetcat

#1466 solution option

2021-02-11 09:44 UTC, tshemsedinov requested changes
We will change it in a different way

2021-02-11 09:44 UTC, tshemsedinov commented on lib/worker.js
> +  const vm = require('vm');
```suggestion
```
All modules are loaded, see `dependencies.js`

2021-02-11 09:44 UTC, tshemsedinov commented on lib/worker.js
> +  const sandbox = { PORT: parseInt(process.env.PORT || 0) };
```suggestion
  const sandbox = { process };
```
Not a good place for parsing ports, we can just pass process into sandbox here.

2021-02-11 09:44 UTC, tshemsedinov commented on lib/worker.js
> +
```suggestion
  const context = metavm.createContext(sandbox);
```
Use metavm here

2021-02-11 09:44 UTC, tshemsedinov commented on lib/worker.js
> +  const options = { mode: process.env.MODE, sandbox };
```suggestion
  const options = { mode: process.env.MODE, context };
```
We will rename sandbox to context in `metarhia/config` first, so `sandbox` will be used just in `impress` or other upper-level code but both `metavm` and `metarhia/config` will use `{ context }` in `options`

2021-02-11 11:18 UTC, imnetcat commented
Okey, great

2021-02-11 20:20 UTC, tshemsedinov commented
Will be landed after this fix https://github.com/metarhia/config/issues/67

2021-02-13 01:50 UTC, tshemsedinov commented
To be landed after https://github.com/metarhia/impress/pull/1468

2021-02-13 01:53 UTC, tshemsedinov commented on lib/worker.js
> +  const context = metarhia.metavm.createContext(sandbox);
```suggestion
  const context = metarhia.metavm.createContext({ process });
```

2021-02-13 02:31 UTC, tshemsedinov commented on lib/worker.js
>    const configPath = path.join(application.path, 'config');
```suggestion
  const configPath = path.join(application.path, 'config');
  const context = metarhia.metavm.createContext({ process });
```

2021-02-13 02:53 UTC, tshemsedinov commented
Landed in https://github.com/metarhia/impress/commit/4c4098802de80be220bf955eab64e9492679456c

2021-02-13 02:53 UTC, closed without merging